### ISSUE TITLE
Rules

### ISSUE THREAD

**Issue by robmcguinness** [Availity/eslint-config-availity#169]
## Disable 

- `no-restricted-syntax` - needed for processing streams of data
- `global-require` - good for lazy require
- `arrow-parens` - conflicts with pretteir

**Comment by robmcguinness** [comment]
`eslint-config-prettier` disabled `arror-parens` https://github.com/prettier/eslint-config-prettier/blob/master/index.js#L25 but somehow our configuration still enforces the conflicting rule.

**Comment by nylon22** [comment]
strange. it looks like we disable arrow-parens as well: https://github.com/Availity/eslint-config-availity/blob/94f9bc3d5ee72503338c1cc2a79e3b4a2c474a97/base.js#L60

**Comment by nylon22** [comment]
we were on an older version of eslint-config-prettier. i'm working on a PR now that upgrades to the latest and uses the default value.
