### ISSUE TITLE
Investigate eslint-plugin-compat

### ISSUE THREAD

**Issue by robmcguinness** [Availity/eslint-config-availity#24]
https://github.com/amilajack/eslint-plugin-compat

**Comment by robmcguinness** [comment]
several teams keep using `includes` for strings and arrays that break IE 11. I wonder if this plugin should can help mitigate this problem (among other IE bugs).

**Comment by GoPro16** [comment]
I just tried this out and it doesn't seem to catch the `includes` method when linting

**Comment by robmcguinness** [comment]
bummer. now looking at https://www.npmjs.com/package/eslint-plugin-ie11

**Comment by robmcguinness** [comment]
Closing since the plugin doesn't handle instance methods on strings.
