### ISSUE TITLE
Upgrade eslint-plugin-unicorn

### ISSUE THREAD

**Issue by robmcguinness** [Availity/eslint-config-availity#27]
https://github.com/sindresorhus/eslint-plugin-unicorn/releases/tag/v8.0.0

Disable `prefer-includes` since it is not supported by IE11.

**Comment by TheSharpieOne** [comment]
Probably want to also disable `prefer-node-remove` since `ChildNode.remove()` is not also supported by IE (not that anyone is really removing nodes in that fashion)
