### ISSUE TITLE
Latest version failed to load plugin 'jest'

### ISSUE THREAD

**Issue by diegodesouza** [Availity/eslint-config-availity#288]
I've just updated to the latest version and now I'm getting the following error
```
ERROR in Failed to load plugin 'jest' declared in 'BaseConfig » eslint-config-availity/workflow': Class extends value undefined is not a constructor or null
Referenced from: .../node_modules/eslint-config-availity/workflow.js
```

Have you seen this before?

**Comment by diegodesouza** [comment]
I've just installed `jest` in my project, this did not fix the issue.

**Comment by jordan-a-young** [comment]
Can you produce a codesandbox or push a link to the repo where this is happening? I have not seen this issue before. If you're able, I would try deleting the lockfile and reinstall everything to make sure things were updated properly.

**Comment by diegodesouza** [comment]
Sure @jordan-a-young I'm trying to reproduce it in a codesandbox, I noticed that when i upgrade 
`eslint-config-availity` and not `eslint` to the latest i do not see the issue.

**Comment by diegodesouza** [comment]
I'm not sure what it is yet other than the two packages conflicting with each other, doesn't happen in the codesandbbox https://codesandbox.io/s/relaxed-bird-5kpk2
