### ISSUE TITLE
Reconsider linebreak-style

### ISSUE THREAD

**Issue by robmcguinness** [Availity/eslint-config-availity#29]
Need to figure out if this rule is worth keeping vs the noise it makes when editors are not configured for `LF`

**Comment by GoPro16** [comment]
One downside of disabling this is if you have 2 developers that are working on the same code each PR  will have a diff for each of those line style changes instead of erroring.

**Comment by TheSharpieOne** [comment]
doesn't git help enforce some of this: `text eol=lf`

> Git will always convert line endings to `LF` on checkout. You should use this for files that must keep LF endings, even on Windows.

and as far as editors, there are "universal" configurations[ which most editors can consume by default or have a plugin to consume](https://editorconfig.org/#download). Like `.editorconfig`
https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#end_of_line

**Comment by robmcguinness** [comment]
@TheSharpieOne Eslint docs suggest maybe handling this through `.gitattributes` as well. The problem with `.editorconfig` is that we rely on the editor having correct plugin.

https://eslint.org/docs/rules/linebreak-style#using-this-rule-with-version-control-systems

**Comment by TheSharpieOne** [comment]
IMHO, this is similar to tabs vs spaces and even the number of spaces. We enforce those standards whether or not the editor makes noise or not.
Editor configs help, but at the end of the day people need to follow the project conventions and PRs need to be declined if they don't.
Plus, we would rely on the editor having an eslint plugin in order for it to make noise.

**Comment by robmcguinness** [comment]
consensus was to leave as is.
