### ISSUE TITLE
Parsing error after updating react version for eslint-plugin-availity

### ISSUE THREAD

**Issue by AlpeshMN** [Availity/eslint-config-availity#30]
Hi Team,
We are facing issue on ESLINT. It was working fine for old version of React. After updating React to 16.8, it shows Parsing Error. Attached is the screen shot of Error. I have attached my package.json file and eslintrc.yaml file here. Please help me out from this issue.

========
.eslintrc.yaml file code below

`---
extends: eslint-config-availity
globals:
  afterEach: true
  beforeEach: true
  describe: true
  it: true `

`{
  "name": "...",
  "version": "2.6.0",
  "private": true,
  "description": "Example React project using availity-workflow",
  "main": "index.js",
  "scripts": {
    "start": "av start",
    "av": "av",
    "test": "av test",
    "test:watch": "av test --watch",
    "test:integration": "av test",
    "test:coverage": "av test --coverage",
    "about": "av about",
    "lint": "av lint",
    "help": "av help",
    "profile": "av profile",
    "build": "av build",
    "build:production": "cross-env NODE_ENV=production av build",
    "build:staging": "cross-env NODE_ENV=staging av build",
    "release": "av release",
    "production": "cross-env NODE_ENV=production av release",
    "staging": "cross-env NODE_ENV=staging av release"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/availity/availity-workflow.git"
  },
  "keywords": [
    "react",
    "availity",
    "workflow"
  ],
  "author": "Robert McGuinness",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/availity/availity-workflow/issues"
  },
  "homepage": "https://github.com/availity/availity-workflow#readme",
  "dependencies": {
    "@availity/api-axios": "^5.1.1",
    "@availity/api-core": "^5.1.1",
    "@availity/breadcrumbs-spaces-react": "^1.6.0",
    "@availity/localstorage-core": "^2.6.1",
    "availity-reactstrap-validation": "^2.5.1",
    "availity-uikit": "^3.0.0-beta.13",
    "axios": "^0.18.0",
    "es6-promise": "^4.2.6",
    "es6-symbol": "^3.1.1",
    "isomorphic-fetch": "^2.2.1",
    "lodash.map": "^4.6.0",
    "mobx": "^5.9.0",
    "mobx-react": "^5.4.3",
    "prop-types": "^15.7.2",
    "react": "^16.8.0",
    "react-block-ui": "^1.1.3",
    "react-dom": "^16.8.0",
    "react-router-dom": "^5.0.0",
    "react-select": "^2.4.3",
    "react-transition-group": "^4.0.0",
    "reactstrap": "^7.1.0"
  },
  "devDependencies": {
    "availity-workflow": "^3.2.0",
    "availity-workflow-react": "^3.2.1",
    "babel-eslint": "^10.0.1",
    "chai": "^4.2.0",
    "cross-env": "^5.2.0",
    "enzyme": "^3.9.0",
    "eslint": "^5.16.0",
    "eslint-config-availity": "^4.0.2",
    "eslint-plugin-import": "^2.17.2",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-react": "^7.12.4",
    "moment": "^2.24.0",
    "moxios": "^0.4.0",
    "react-test-renderer": "^16.8.6",
    "sinon": "^7.3.2",
    "sinon-chai": "^3.3.0"
  },
  "availityWorkflow": {
    "plugin": "availity-workflow-react"
  }
}

`

<img width="793" alt="Screen Shot 2019-04-26 at 12 23 14 PM" src="https://user-images.githubusercontent.com/37811280/56822348-c1b9d600-681e-11e9-92d4-f373c5069051.png">

**Comment by AlpeshMN** [comment]
@robmcguinness

**Comment by robmcguinness** [comment]
➡️  Delete the following from `devDependencies` since those are now dependencies of the `eslint-config-availity` module:

- babel-eslint
- eslint
- eslint-plugin-import
- eslint-plugin-jsx-a11y
- eslint-plugin-react

➡️  Upgrade `@availity/workflow` and `@availity/workflow-plugin-react`Also

➡️ remove the following from `package.json` and any reference in your code:

- es6-promise
- es6-symbol
