### ISSUE TITLE
Error in Baseconfig

### ISSUE THREAD

**Issue by bryanmorganoverbey** [Availity/eslint-config-availity#322]
node --version
v14.17.6

yarn --version
3.2.1

I don't have an eslintrc.yml in this project, so it picks up the base config and throws this error:

Error in BaseConfig » eslint-config-availity/workflow:
        Configuration for rule "unicorn/numeric-separators-style" is invalid:
        Value {"onlyIfContainsSeparator":true} should NOT have additional properties.

**Comment by chrishavekost** [comment]
Hey @bryanmorganoverbey , can you post your `dependencies` and `devDependencies` from `package.json`? There may be some conflicting packages causing this issue, not sure it's actually a problem with the base configuration

https://github.com/Availity/eslint-config-availity/blame/4226d71bdb68ac2bfde3a1b84cccc1ba820840eb/base.js#L68
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/51d7e06b6f3fa803cdfacda7dc52981472934870/docs/rules/numeric-separators-style.md#options
